// Generated by CoffeeScript 1.7.1
var MongoClient, format;

MongoClient = require('mongodb').MongoClient;

format = require('util').format;

MongoClient.connect('mongodb://localhost/igor_results', function(err, db) {
  if (err) {
    throw err;
  }
  console.log("Connect to Database");
  return db.createCollection('');
});
